# Cleans all intermediary files generated by the Raboniel tool (.kiss, .tlsf, _R*.tsl)
# python3 cleanup.py

import os
import re

# Define the folder path containing the benchmark files
raboniel_benchmarks_folder_path = './'

# Define the regular expression pattern for intermediate files of the form _R[0-9]+.tsl. Eg: "_R0.tsl". We do not want to synthesize for these files.
pattern = r"_R\d+\.tsl"

# Cleanup all intermediate files (.kiss, .tlsf, _R*.tsl)
files = os.listdir(raboniel_benchmarks_folder_path)

for file in files:
    # Check if the file matches the patterns
    if re.search(pattern, file) or file.endswith('.tlsf') or file.endswith('.kiss'):
        # Construct the file path
        file_path = os.path.join(raboniel_benchmarks_folder_path, file)
        
        # Delete the file
        os.remove(file_path)