#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2010-2011, 2014-2016, 2018-2020 Laboratoire de Recherche
# et Developpement de l'EPITA (LRDE).
# Copyright (C) 2003, 2004 Laboratoire d'Informatique de Paris 6
# (LIP6), département Systèmes Répartis Coopératifs (SRC), Université
# Pierre et Marie Curie.
#
# This file is part of Spot, a model checking library.
#
# Spot is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Spot is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Darwin needs some help in figuring out where non-installed libtool
# libraries are (on this platform libtool encodes the expected final
# path of dependent libraries in each library).
modpath='/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/python/.libs:/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/python/spot/.libs'
modpath=$modpath:'/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/spot/ltsmin/.libs'
modpath=$modpath:'/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/spot/gen/.libs'
modpath=$modpath:'/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/spot/.libs'
modpath=$modpath:'/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/buddy/src/.libs'

# We need access to both the *.py files, and the *.so.  We used to
# rely on a module called ltihooks.py to teach the import function how
# to load a Libtool library, but it started to cause issues with
# Python 2.6.
pypath=
for i in python python/spot; do
    for j in '/home/stanley/Projects/gensysMain/gensys/spot-2.9.8' '/home/stanley/Projects/gensysMain/gensys/spot-2.9.8'; do
	pypath=$j/$i:$j/$i/.libs:$pypath
    done
done
pypath=${pypath%:}

PATH="/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/bin:$PATH"
export PATH

test -z "$1" &&
    PYTHONPATH=$pypath DYLD_LIBRARY_PATH=$modpath:$DYLD_LIBRARY_PATH \
    exec $PREFIXCMD /usr/bin/python3
srcdir="."

# Reset CFLAGS, because some tests call the compiler, and we do not
# want to inherit parameters likes -std=c11 -fvisibility=hidden
CFLAGS=
export CFLAGS
CXX='g++ -std=gnu++11'
export CXX
CXXFLAGS=' -fvisibility=hidden -fvisibility-inlines-hidden -DSPOT_BUILD -std=c++14 -g -O3 -ffast-math -fstrict-aliasing -fomit-frame-pointer'
export CXXFLAGS
top_builddir='/home/stanley/Projects/gensysMain/gensys/spot-2.9.8'
export top_builddir
top_srcdir='/home/stanley/Projects/gensysMain/gensys/spot-2.9.8'
export top_srcdir

PERL='perl'
export PERL

# Reset those variables, as they may affect the output of DOT.
SPOT_DOTEXTRA=
export SPOT_DOTEXTRA
SPOT_DOTDEFAULT=
export SPOT_DOTDEFAULT=

SPOT_UNINSTALLED=1
export SPOT_UNINSTALLED

case $1 in
    */*)
	dir=${1%/*}
	dir=${dir##*/}
	mkdir -p $dir
	cd $dir
	case $1 in
	    ../*)
		base=../$1
		;;
	    [\\/$]* | ?:[\\/]* )
		base=$1
		;;
	    *)
		base=${1##*/}
		;;
	esac

	test $srcdir != '.' && srcdir="/home/stanley/Projects/gensysMain/gensys/spot-2.9.8/tests/$dir"
        shift
        set x "$base" "$@"
	shift
	;;
esac

export srcdir

case $1 in
  *.ipynb)
    PYTHONPATH=$pypath DYLD_LIBRARY_PATH=$modpath:$DYLD_LIBRARY_PATH \
    PYTHONIOENCODING=utf-8:surrogateescape \
    exec $PREFIXCMD /usr/bin/python3 /home/stanley/Projects/gensysMain/gensys/spot-2.9.8/tests/python/ipnbdoctest.py "$@";;
  *.py)
    PYTHONPATH=$pypath DYLD_LIBRARY_PATH=$modpath:$DYLD_LIBRARY_PATH \
    exec $PREFIXCMD /usr/bin/python3 "$@";;
  *.test)
    exec sh -x "$@";;
  *.pl)
    exec $PERL "$@";;
  *python*|*jupyter*)
    PYTHONPATH=$pypath DYLD_LIBRARY_PATH=$modpath:$DYLD_LIBRARY_PATH \
    exec $PREFIXCMD "$@";;
  *)
    echo "Unknown extension" >&2
    exit 2;;
esac
